name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
    
    - name: Create buildozer.spec for cloud build
      run: |
        cat > buildozer.spec << 'EOF'
        [app]
        title = Performance Tracker
        package.name = performancetracker
        package.domain = com.blackwolf.performancetracker
        source.dir = .
        source.include_exts = py,png,jpg,kv,atlas,txt,db
        version = 1.0
        requirements = python3,kivy==2.3.1,kivymd==1.0.2,numpy,pandas,matplotlib
        [buildozer]
        log_level = 2
        [android]
        api = 33
        minapi = 21
        ndk = 25b
        sdk = 33
        archs = arm64-v8a
        allow_backup = True
        EOF
    
    - name: Build APK
      run: |
        buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: performance-tracker-apk
        path: bin/*.apk

    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0-${{ github.run_number }}
        name: Performance Tracker v1.0-${{ github.run_number }}
        files: bin/*.apk
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 